### ISSUE TITLE
[Feature Request] Challonge API Integration

### ISSUE THREAD

**Issue by VeeZG** [PhlexPlexico/G5API#125]
Is it possible to create a connection with G5API + Challonge. Many will find it useful to create their own tournaments. The names of the teams with challonge and g5api must match on the grid.

**Comment by PhlexPlexico** [comment]
Okay, I started looking into the API calls for Challonge and I do have a question for this. Would you have the teams created beforehand? I'm unsure how you would get team players inserted into the application itself... I think if you wanted something a bit more feature complete I think it would be better to go with Toornament as seen in this issue here https://github.com/PhlexPlexico/G5V/issues/28

I'm still unsure on how to continue with this as Toornament does allow for full teams and information as well as match setups.

**Comment by PhlexPlexico** [comment]
Going to close this issue as I think I've outlined a better approach in the linked issue.
