### ISSUE TITLE
[BUG] Invalid Steam IDs Pass as Valid

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5API#131]
**Describe the bug**
This nick: ✪ s p a r k u s makes the team error-out. probably just another sanitization error. But even if I force a nick, it still wont come back

**To Reproduce**
Add this SID to a team: 76561198098962600

**Expected behavior**
player loaded same as others

**Screenshots**
![image](https://user-images.githubusercontent.com/26146502/137759540-b2dd9d75-0742-471a-b62a-19fd68970d2d.png)

**Server info**
 - https://cs.jakubdobos.eu/api/teams/3

**Comment by kubo6472** [comment]
okay, this happens with too much stuff. finally found the error logs, and they are 150 000 lines long. oof

**Comment by PhlexPlexico** [comment]
Yeah right now there isn't any log rotations in place... Should really look into some PM2 settings to make it easier for users to setup. However, what do you mean this happens with too much stuff? Thanks for putting it in the public panel, I can take a look into it here.

**Comment by kubo6472** [comment]
Also: 
![image](https://user-images.githubusercontent.com/26146502/137766336-3eb4f08c-9837-48d7-a9dc-6883b36b7496.png)
the veto_side is still empty, but I think I should open a new issue for that, right?

**Comment by PhlexPlexico** [comment]
Huh, so funny thing about that steam profile. It seems that it does exist (according to Steam's own API calls), however the account is failing to load data. I believe that if there are errornous values, they just won't be added into the team_auths. Very weird case but there isn't much I can do since steam reports it as an existing account.
