### ISSUE TITLE
[Request] Is it possible to authenticate againts the API without signing in through steam? 

### ISSUE THREAD

**Issue by Emil8250** [PhlexPlexico/G5API#150]
Hi! 

I'm currently trying to create a simple frontend, which uses your API to create teams and matches in GET5.
If I sign-in through your web panel, steals my steam session cookie and uses it to make API calls, everything works great. 
However, I'd love to avoid signing in first, is it possible to authenticate using an API key instead? Or do I have to implement steam signin on my own site? :-)

**Comment by PhlexPlexico** [comment]
Hi!

(Un)fortunately the only way to sign in to the API is through steam. I figured using this as an OAuth method and using passport was the easiest to implement, and most people who would be using the tool would be using Steam. However, once you login with a user, you are indeed granted an API key, which can be viewed on requests to `/user/:id` (if it is your user, or you're a super admin). This API key can either be sent in as the body of a POST request, or within the header (use key `user-api` as seen (here)[https://github.com/PhlexPlexico/G5API/blob/b8fa04e2e2cbd983cbd5d1c62e515ca5adf9c2b9/utility/utils.js#L133]).

I prefer not to include any other sign ins (especially non-oauth) as I do not wish to keep a database of username/passwords simply due to the risk (in that I do not trust myself with secure coding). 

Also, once you sign in and get an API key, you can always use that unless you wish to re-generate one, no more sign ins would be necessary :)

**Comment by Emil8250** [comment]
Hi agian! 

Thanks for the quick and precise response. This was EXACTLY what i wanted :) 

Hope you have a nice day, and thanks for a nice project.

**Comment by PhlexPlexico** [comment]
Anytime! Whenever your project is finished and you'd like to have it featured on this repo just create a pr and update the readme :)

**Comment by PhlexPlexico** [comment]
Closing since this has appeared to been answered :)
