### ISSUE TITLE
[Request] Caddy reverse proxy support for local network (raspberrypi.local)

### ISSUE THREAD

**Issue by xe1os** [PhlexPlexico/G5API#218]
**Is your feature request related to a problem? Please describe.**
Request

**Describe the solution you'd like**
Support for caddy (SSL) on hosting G5API & G5V over lan network as localhost or local domain using samba (hostname.local)

**Describe alternatives you've considered**
No.

**Additional context**
Configuration that can be managed easily if it has to be hosted on local or WAN

**Comment by PhlexPlexico** [comment]
I don't think I'll be supporting this, as it seems to be quite an edge case. You can disable HTTPS and just use HTTP, per this comment.

https://github.com/PhlexPlexico/G5API/issues/216#issuecomment-1206017099

If you wish to set something up like this, feel free to create some documentation. The docker-compose is mainly used for quick setup for general use cases. I think this request is fairly out of scope, since it is another technology being used (I only use it in the docker-compose as an example of what could be done).

With some quick Googling, I was able to find some information on how this could be done with Caddy. One way would be to create your own Caddyfile which you can use `CADDY_DOCKER_CADDYFILE_PATH` I believe.

Another way, is to disable verifying certs, you can use the following options on the caddy labels;
```
caddy.reverse_proxy.transport: "http"
caddy.reverse_proxy.transport.tls_insecure_skip_verify:
```

If you wish to know more, I believe you can search through the caddy reverse proxy repo that the docker-compose file uses (if you wish to go this route) [here](https://github.com/lucaslorentz/caddy-docker-proxy).
