### ISSUE TITLE
[Tip] Using Prettier to remove formatting problems

### ISSUE THREAD

**Issue by ringvold** [PhlexPlexico/G5API#31]
This is just a tip and the only place I found to post it. I saw you had some commits related to missing semicolons. It happens! 😆 But that problem can be removed completely with [Prettier](https://prettier.io/)! 😄 
Can be used as a plugin in the editor or for example as and pre-commit hook.

You might already be aware, but I though I'd let you know if not. :)

BTW, I'm excited for this new project and I'm planning to create a frontend for it so I'm kind of just stalking the repo until I get around to start on it. I'm hoping to contributing to this project as well but its not on the top of my priorities yet. I hope to get some time for it! Awesome to see progress here! :D

**Comment by PhlexPlexico** [comment]
Hey! Thanks for the tip! I'm actually using prettier, however my main development machine isn't properly setup with it, whereas my secondary is 😅 hence the 1AM commits where I forgot a bracket or semi-colon is missed, is because Prettier isn't configured properly, which I should setup, but I'm open for tips on setup honestly! 

As for the front-end, that sounds amazing! I can't wait to see it, I can even setup a portion in the README, too!
