### ISSUE TITLE
[BUG] ERR_HTTP_HEADERS_SENT: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by hoan111** [PhlexPlexico/G5API#57]
Hello!
I installed and configurated both G5API and G5V. But when I go to G5V website, I checked the G5API log and saw the error in the picture below. I cannot login to G5V using Steam. I just want to run the API and G5V on the local network.
The error log:
![image](https://user-images.githubusercontent.com/32768392/99141815-84779c00-2681-11eb-88d3-1ab0b98284d4.png)
My configuration files:

> Development.json

![image](https://user-images.githubusercontent.com/32768392/99141761-0a471780-2681-11eb-8548-2665201c4401.png)

> vue.conf.js
![image](https://user-images.githubusercontent.com/32768392/99141852-cef91880-2681-11eb-9a1f-4495b6bb7585.png)

**Comment by PhlexPlexico** [comment]
Either change the `target` in your `vue.config.js` to `http://localhost:3301` or swap the `hostname` under `Server` in the config.json file to `http://192.168.1.11:3301`

I'll need to look into line 191 on `app.js` as well I suppose, could be something failing there that shouldn't be!

**Comment by hoan111** [comment]
I tried but still no luck :(

**Comment by PhlexPlexico** [comment]
And what happens when you attempt to login? Does it just redirect back to the site? Or what does logging in do? Is the database a brand new instance (i.e. no previous logins etc)?

**Comment by hoan111** [comment]
Yes, it just redirect back to the site. I'm using "Sign in through STEAM" button. The error appears everytime I refresh the website.

**Comment by PhlexPlexico** [comment]
Are you able to provide the full log from application start, to logon to error? It would be a bit easier seeing the full direction path that's going on. What version of node are you using? What's the OS? Are you using yarn or npm?

**Comment by hoan111** [comment]
This is the log from start to logon. The error appeared everytime G5V request to the API server.
[](https://pastebin.com/6eZZEWBB)

I'm currently using NodeJS 13.8.0. Windows 10, and tried both yarn and npm to install dependencies but still got that error. I don't know why :(((
My current configuration:
**developent.json**
![image](https://user-images.githubusercontent.com/32768392/99152944-bb789c80-26d7-11eb-9b8f-361fd530b14b.png)
**vue.conf.js**
![image](https://user-images.githubusercontent.com/32768392/99152960-db0fc500-26d7-11eb-9908-940a4d782812.png)

**Comment by PhlexPlexico** [comment]
Uhhh change your apiURL by the way. That apiURL in the API config has to match the get5vue public url.

As for the headers not being set, it looks like it's trying to error out on something and failing. I would recommend trying to use production mode and see if that works. I'll have to install it on windows and debug. If you would not mind, edit the app.js on this line:

https://github.com/PhlexPlexico/G5API/blob/8f485b0cc439cb50d9c9db25f90b8005793bb4e0/app.js#L186

And add `console.log(err.message);` and see what it produces?

Thanks!

**Comment by PhlexPlexico** [comment]
Okay so here's what I got. Also, next time if you're submitting a bug, please use the issue format, since it provides some really good information that can be used for debugging :)

Node version: 13.13.0 (use `node -v`)
Yarn version: 1.22.4 (use `yarn -v`)
OS: Windows 10

And here's my config. Instead of using local host I opted for my PC's internal IP across everything.

![image](https://user-images.githubusercontent.com/3514085/99154852-8c7f0e00-2678-11eb-812e-10618caec8da.png)


It's always possible it could be a Steam -> API connection issue. In which case, use the above comment and paste in the bug here, and provide the output.

**Comment by hoan111** [comment]
Still got the same error. Can you share your current package.json using on Windows? I think the problem may come from my edit of package.json. I used NodeJS 13.13.0, Yarn 1.22.4, and npm to install dependencies.
My current package.json:
![image](https://user-images.githubusercontent.com/32768392/99193057-07dfdd00-27a9-11eb-88a5-f134cb3866cd.png)

**Comment by PhlexPlexico** [comment]
It shouldn't have to do with the `package.json` as that is just a few scripts to help with setup/running the app. Unless you modified the dependencies at all, there should be no difference in that. Please attempt what I had put in this comment below, and grab the error message from your console before that fails.

Thanks!

> 
> 
> Uhhh change your apiURL by the way. That apiURL in the API config has to match the get5vue public url.
> 
> As for the headers not being set, it looks like it's trying to error out on something and failing. I would recommend trying to use production mode and see if that works. I'll have to install it on windows and debug. If you would not mind, edit the app.js on this line:
> 
> https://github.com/PhlexPlexico/G5API/blob/8f485b0cc439cb50d9c9db25f90b8005793bb4e0/app.js#L186
> 
> And add `console.log(err.message);` and see what it produces?
> 
> Thanks!

**Comment by hoan111** [comment]
I received this error: "ERR wrong number of arguments for 'set' command". This can be from my package.json. I should try to restore the original file and let you know if it work!

> It shouldn't have to do with the `package.json` as that is just a few scripts to help with setup/running the app. Unless you modified the dependencies at all, there should be no difference in that. Please attempt what I had put in this comment below, and grab the error message from your console before that fails.
> 
> Thanks!
> 
> > Uhhh change your apiURL by the way. That apiURL in the API config has to match the get5vue public url.
> > As for the headers not being set, it looks like it's trying to error out on something and failing. I would recommend trying to use production mode and see if that works. I'll have to install it on windows and debug. If you would not mind, edit the app.js on this line:
> > https://github.com/PhlexPlexico/G5API/blob/8f485b0cc439cb50d9c9db25f90b8005793bb4e0/app.js#L186
> > 
> > And add `console.log(err.message);` and see what it produces?
> > Thanks!

**Comment by hoan111** [comment]
Steps I migrated the database:
1. type "set MYSQL_FLAGS=\"-CONNECT_WITH_DB\" db-migrate --env production --config config/production.json db:create get5"
2. type "yarn migrate-prod-upgrade"

The result I got:
![image](https://user-images.githubusercontent.com/32768392/99212891-d0038480-27fe-11eb-9d5f-5bba43083c39.png)

**Comment by PhlexPlexico** [comment]
So you got it resolved then?

**Comment by hoan111** [comment]
Nope :( I'm still trying for 6 hours ago but still no luck. I installed Ubuntu WSL but the error still appear

**Comment by hoan111** [comment]
Nope :( I have tried for 6 hours ago but it's still not working. I installed Ubuntu WSL to have a fresh install but this didn't work. I think the problem could come from the configuration.

**Comment by hoan111** [comment]
I tried with my hostname but I got the error "Invalid host header" when I access to the hostname.

**Comment by PhlexPlexico** [comment]
Okay. So a few things to iron out here.

> 
> 
> Steps I migrated the database:
> 
>     1. type "set MYSQL_FLAGS="-CONNECT_WITH_DB" db-migrate --env production --config config/production.json db:create get5"
> 
>     2. type "yarn migrate-prod-upgrade"
> 
> 
> The result I got:
> ![image](https://user-images.githubusercontent.com/32768392/99212891-d0038480-27fe-11eb-9d5f-5bba43083c39.png)

With this, I'm not sure if this is what you've always been doing, but if you're using Git on windows through Git Bash, you'll see it says "MinGW64", which is an alternative to Cygwin, which is a Linux Shell for windows (for this use case let's say). So using `set` will not work here. When I said try changing it over to set, I assumed you were going to be using `Powershell` or `cmd`, which is directly native to windows. So, if you're using Windows, please only use `git` to clone the project down, then switch over to `cmd` or `Powershell` and adjust your scripts as needed. Secondly, all of this can be mitigated with the following I had said [here](https://github.com/PhlexPlexico/G5API/issues/43#issuecomment-726768123_). If you login to your database, create the get5 database, you can just then run `yarn migrate-prod-upgrade` which will then upgrade the database. No configuration needs to be done for `package.json`.



> 
> 
> I tried with my hostname but I got the error "Invalid host header" when I access to the hostname.
> E: I'm trying with my public server. I will let you know if it work

Depending on how you're launching G5V, this can be due to a myriad of errors. Honestly, I tried working with both `nginx` and `apache2` to figure out how to get reverse proxies working for everything and wasted a ton of time, because a lot more research is needed on my part. For now, I would recommend using the `yarn serve` command there, and updating the two following lines. The first one, `public`, to be your outward-facing public URL:
https://github.com/PhlexPlexico/G5V/blob/master/vue.config.js#L4

The second, depending if it's on the same machine or not (which I assume it is), could possibly be left, but I would recommend setting it to whatever the IP is of your local machine:

https://github.com/PhlexPlexico/G5V/blob/master/vue.config.js#L7

Lastly, in order for me to continue helping, please do the following if errors still persist as it will (hopefully!) tell you _exactly what's wrong_!


https://github.com/PhlexPlexico/G5API/blob/8f485b0cc439cb50d9c9db25f90b8005793bb4e0/app.js#L186

And add `console.log(err.message);` and see what it produces?

Thanks.

**Comment by hoan111** [comment]
ok, this is the error log after I added `console.log(err.message);` to line 186. 
![image](https://user-images.githubusercontent.com/32768392/99275869-97939300-285e-11eb-9797-f8b2eb179d8d.png)

**Comment by PhlexPlexico** [comment]
Hm. Are you using redis by chance?

**Comment by hoan111** [comment]
Yes. I'm currently using Redis

**Comment by PhlexPlexico** [comment]
On Windows? And what version of redis are you running?

**Comment by hoan111** [comment]
If you can please share your current config you're using on your G5V website http://phlex.avidgamers.me:8080/ and what type of webserver. I will follow this to reconfigure for myself. 


> On Windows? And what version of redis are you running?

Yes. On Windows. Redis version 2.4.5

**Comment by PhlexPlexico** [comment]
Seems to be the problem. After some searching for the error message, I came across this:

**Comment by hoan111** [comment]
Oh yeah, man. It's workedddddddd. I can go to sleep now. Thank you and have a good day :D

**Comment by PhlexPlexico** [comment]
You as well :) glad we could resolve this!
