### ISSUE TITLE
[BUG]  Failed to load match config, Steamworks GET request failed, HTTP status code = 0

### ISSUE THREAD

**Issue by xe1os** [PhlexPlexico/G5API#58]
**Describe the bug**
Match doesn't start on the csgo server after creating match in G5V

**To Reproduce**
1. Go to `G5V Web Panel`
2. Click on `Create A Match`
3. Message displayed on G5V  `Successfully registered match.`
4. Error in csgo server console `[get5.smx] Failed to load match config: Steamworks GET request failed, HTTP status code = 0`

**Expected behavior**
Match should get created and map should change.

**Screenshots**
![Steamworks error](https://user-images.githubusercontent.com/39219862/99179731-5c05a580-2746-11eb-8608-970756a82936.jpg)

![plugins list](https://user-images.githubusercontent.com/39219862/99179736-63c54a00-2746-11eb-8e54-cebfa7d0fe46.jpg)

![extensions list](https://user-images.githubusercontent.com/39219862/99179737-64f67700-2746-11eb-94b0-321dad48734d.jpg)

**Desktop (please complete the following information):**

**Server info
 - OS: [macOS Catalina]
 - Version [10.15.2]
 - NodeJS version (13.8.0)

**Additional context**
Updated `Steamworks`

**Comment by PhlexPlexico** [comment]
Are you able to post your match config? It's located `http://servername.com/API/matches/{matchid}/config` and please provide the output. Make sure G5API is also up to date. If we can look at the config we can see what's wrong. I suspect you're trying to load the match locally, which will not work. You'll have to expose the panel as your public IP (and ports 8080&3301) if not using a host. This includes the case on local LANs I believe? It's been awhile since I've ran into the issue, but I vaguely remember steamworks having that problem.

**Comment by PhlexPlexico** [comment]
Also if possible, please reproduce this with `get5_debug 32` according to [here](https://github.com/splewis/get5/wiki/Debugging-help). It provides much more info than just "failed to load" :)

**Comment by xe1os** [comment]
> Are you able to post your match config? It's located `http://servername.com/API/matches/{matchid}/config` and please provide the output. Make sure G5API is also up to date. If we can look at the config we can see what's wrong. I suspect you're trying to load the match locally, which will not work. You'll have to expose the panel as your public IP (and ports 8080&3301) if not using a host. This includes the case on local LANs I believe? It's been awhile since I've ran into the issue, but I vaguely remember steamworks having that problem.

@PhlexPlexico Yes. I'm trying to test locally(LAN). Both hosted G5V and csgo server are on the same LAN Network. Is it possible to have a LAN version of both G5V and G5API? If this cant be done now then i can expose the panel on public and do the testing. Will report incase if i come across any bugs.

**Comment by hoan111** [comment]
Same problem with you @xe1os  but when G5V said` successfully registered match` I checked the server the map didn't change, nothing else happened :(
![image](https://user-images.githubusercontent.com/32768392/99282724-a5e5ad00-2866-11eb-8bb4-1b57eb17be59.png)

**Comment by PhlexPlexico** [comment]
Soooooo I'm not sure where you guys are getting the idea that the map should change. 

That used to be a quick hack fix to ensure some CVARs were properly set (like `get5_check_auths`). I no longer do this since it's just bad practice and teams will get sorted once veto is done. If you're running a tournament that option should be set anyways as a default in your `get5.cfg`.

@xe1os 
I've tried running local, but do not have a CS:GO server to try local with. What I did was expose the ports `3301` and `8080` and tried a few remote servers (DatHost, FShost, a personal friend's server) to see if it was working as intended. I wouldn't see why running local wouldn't work, since you're just reporting to the same internal IP, unless SteamWorks is doing something funky. I'm not sure.

@hoan111 it looks like you're missing `system2.ext.dll` on your Windows box, which may cause issues? I'm not so sure. It looks like the system is working as intended for you, as it did get the `get5_web_available` call and returned, and there is no errors as well. Much like above, if you wouldn't mind, set `get5_debug 32` and then retrieve the file to upload here. I'm assuming yours is working as intended and you should see in your console `use !ready to start` or something of the like.

But once again, turn on debugging and provide the output and I can help out as well, I've never ran into these issues personally.

**Comment by hoan111** [comment]
Here's my log get5 debug
```
L 11/17/2020 - 00:29:23: [get5] cleanedUrl (SteamWorks) = http://192.168.1.11:8080/api//matches/4/config
L 11/17/2020 - 00:29:23: [get5_api] get5_web_api_url now set to 
L 11/17/2020 - 00:29:23: [get5] get5_event: {"matchid`":"","params":{"reason":"invalid match json"},"event":"match_config_load_fail"}
```

**Comment by PhlexPlexico** [comment]
please navigate to http://192.168.1.11:8080/api//matches/4/config on your network and paste the config as well :) looks like get5_web_api_url isn't being set either, but that could just be a race condition because I've seen that before and haven't had issues. Make sure you're `apiURL` does not have that leading slash as well in your config.

`"apiURL": "http://192.168.1.11:8080/api"` instead of `"apiURL": "http://192.168.1.11:8080/api/"

**Comment by hoan111** [comment]
Here's the config at http://192.168.1.11:8080/api//matches/6/config. The problem I think comes from rcon commands is not being sent to the game server.
`{"matchid":"6","match_title":"Map {MAPNUMBER} of {MAXMAPS}","side_type":"always_knife","veto_first":"team1","skip_veto":false,"min_players_to_ready":5,"players_per_team":5,"team1":{"name":"Team 2","tag":"NEW","flag":"VN","matchtext":"Team 2","players":{}},"team2":{"name":"New Team","tag":"NEW","flag":"AT","matchtext":"New Team","players":{}},"cvars":{"get5_web_api_url":"http://192.168.1.11:8080/api/","get5_check_auths":"1"},"spectators":{},"maplist":["de_dust2","de_mirage","de_inferno","de_overpass","de_train","de_nuke","de_vertigo"],"min_spectators_to_ready":0,"maps_to_win":1}`

**Comment by hoan111** [comment]
Good news! Just update the get5 plugin to version 0.7.2-dev. It worked perfectly!
I followed this config
https://github.com/PhlexPlexico/G5API/issues/57#issuecomment-727250475

**Comment by PhlexPlexico** [comment]
@xe1os if you're still running into problems, just set `get5_debug 32` in your console and provide the output here if it's failing, I should be able to help debug a little here if you still need.

**Comment by xe1os** [comment]
@PhlexPlexico Sorry i had by mistake removed port `8080` from the the `apiURL` in the config file. Got to know after using `get5_debug 32` where get5_web_api_url was pointing to `http://192.168.0.101/api` 

It is now working fine now. Thanks for the help :) 👍

**Comment by PhlexPlexico** [comment]
Awesome! I'm glad to hear it's working as intended, and anytime! :)
