### ISSUE TITLE
[BUG] Game server error when adding spectator

### ISSUE THREAD

**Issue by thboss** [PhlexPlexico/G5API#92]
**Describe the bug**
I try to add a spectator to the match using route `/api/matches/:match_id/addspec`
the API send this command to the game server `"get5_addplayer [object Promise] spec"`
but it work for `/api/matches/:match_id/adduser` and the command is something like `"get5_addplayer 76561198181941426 team1"`

**Expected behavior**
API should send a command like `"get5_addplayer 76561198181941426 spec"` to the game server

**Additional context**
request body: `{'user_id': 27, 'user_api': 'my_api_key', 'steam_id': '76561198181941426'}`
response code: `200`

**Comment by PhlexPlexico** [comment]
Yup, looks like I missed out on an `await` when retrieving the steam ID of a user. Should be fixed now!

**Comment by thboss** [comment]
Tested and works fine.

Actually, whole the endpoint `addspec` doesn't make sense, It could just make the `adduser` endpoint supports input team_id `spec` in addition to `team1` and `team2` here
https://github.com/PhlexPlexico/G5API/blob/03394d4c7dc15b34a26ed3d29707b8fe873fdc0a/routes/matches/matchserver.js#L618-L620

**Comment by PhlexPlexico** [comment]
Honestly, it was a port from the old Get5-web. I kept it in there because I wanted to make it as close as possible to the original web app before making my changes, and just never got back there :) personally I wouldn't mind leaving it as such, since I know G5V does rely on that route now. Glad to hear this is resolved though, and I'll look into compacting the route into one new route. I'll make sure to create a PR for it and reference back to this issue if I choose to go that way.
